# -*- coding: utf-8 -*-
"""exp012 w1 k4 revival plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-e30kqRgJh_uoY9SpUp3VklEpUEvwpC9
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import signal
import pandas as pd
from matplotlib.lines import Line2D
from matplotlib.patches import Rectangle
from matplotlib.gridspec import GridSpec
import warnings
warnings.filterwarnings('ignore')

# ============================================================================
# QUANTUM WALK SIMULATION FOR 4-CYCLE
# ============================================================================

def create_coin_operator(rho, delta):
    """
    Create coin operator with standard convention (α = δ, β = 0)
    """
    alpha = delta
    beta = 0

    C = np.array([
        [np.sqrt(rho), np.sqrt(1 - rho) * np.exp(1j * alpha)],
        [np.sqrt(1 - rho) * np.exp(1j * beta), -np.sqrt(rho) * np.exp(1j * (alpha + beta))]
    ], dtype=complex)

    return C


def create_shift_operator(k=4):
    """
    Create shift operator for k-cycle
    """
    dim = 2 * k
    S = np.zeros((dim, dim), dtype=complex)

    # Coin |0⟩ moves forward
    for pos in range(k):
        next_pos = (pos + 1) % k
        S[next_pos, pos] = 1.0

    # Coin |1⟩ moves backward
    for pos in range(k):
        prev_pos = (pos - 1) % k
        S[k + prev_pos, k + pos] = 1.0

    return S


def initialize_state(rho, k=4):
    """
    Initialize state at position 0 with given coin superposition
    """
    dim = 2 * k
    psi = np.zeros(dim, dtype=complex)

    psi[0] = np.sqrt(rho)
    psi[k] = np.sqrt(1 - rho)

    return psi / np.linalg.norm(psi)


def von_neumann_entropy(rho_matrix):
    """
    Compute von Neumann entropy S = -Tr(ρ log₂ ρ)
    """
    eigenvalues = np.linalg.eigvalsh(rho_matrix)
    eigenvalues = np.maximum(eigenvalues, 0)

    entropy = 0
    for p in eigenvalues:
        if p > 1e-12:
            entropy -= p * np.log2(p)

    return entropy


def simulate_quantum_walk(rho, delta, steps=50, k=4):
    """
    Simulate quantum walk and return entropy at each step
    """
    # Create operators
    C = create_coin_operator(rho, delta)
    S = create_shift_operator(k)
    C_full = np.kron(C, np.eye(k))
    U = S @ C_full

    # Initialize state
    psi = initialize_state(rho, k)

    # Store entropy
    entropy = np.zeros(steps + 1)

    # Initial entropy
    psi_reshaped = psi.reshape(2, k)
    rho_coin = psi_reshaped @ psi_reshaped.conj().T
    entropy[0] = von_neumann_entropy(rho_coin)

    # Time evolution
    for t in range(1, steps + 1):
        psi = U @ psi
        psi_reshaped = psi.reshape(2, k)
        rho_coin = psi_reshaped @ psi_reshaped.conj().T
        entropy[t] = von_neumann_entropy(rho_coin)

    return entropy


# ============================================================================
# REVIVAL PARAMETERS FROM DUKES (2014) TABLE 4
# ============================================================================

def create_revival_table_4cycle():
    """
    Create DataFrame with all 30 revival parameters for 4-cycle from Dukes (2014) Table 4
    """
    # Data from Dukes (2014) Table 4
    data = {
        'Label': [f'R{i}' for i in range(1, 31)],
        'rho': [
            0.5, 0.5, 0.75, 0.5, 0.5, 0.75, 0.5, 0.5, 0.5, 0.5,
            0.8, 2/3, 0.5, 0.5, 0.75, 0.5, 0.5, 0.9, 2/3, 0.5,
            0.5, 3/4, 0.5, 0.5, 0.75, 0.5, 0.5, 0.8, 0.5, 0.5
        ],
        'delta_over_pi': [
            0.0, 1.0, 0.0, 0.5, 1.5, 1.0, 0.0, 1.0, 0.5, 1.5,
            0.0, 1.5, 0.0, 1.0, 0.0, 0.5, 1.5, 0.0, 0.5, 0.0,
            1.0, 0.5, 0.5, 1.5, 1.0, 0.0, 1.0, 1.0, 0.5, 1.5
        ],
        'N_revival': [
            6, 6, 6, 8, 8, 8, 10, 10, 12, 12,
            12, 12, 14, 14, 14, 16, 16, 16, 16, 18,
            18, 18, 20, 20, 20, 22, 22, 22, 24, 24
        ]
    }

    # Calculate delta
    data['delta'] = [d * np.pi for d in data['delta_over_pi']]

    # Add preliminary classification
    classifications = []
    for i in range(len(data['Label'])):
        rho = data['rho'][i]
        delta_pi = data['delta_over_pi'][i]

        if rho == 0.5:
            if delta_pi in [0.5, 1.5]:
                classifications.append('Class I (Perfect Alternating)')
            else:
                classifications.append('Class II (Fast Alternating)')
        elif rho == 2/3 or rho == 3/4:
            if delta_pi in [0.5, 1.5]:
                classifications.append('Class IIIa (High-Entropy Sustained)')
            else:
                classifications.append('Class IIIb (Complex Multi-Mode)')
        else:
            classifications.append('Class IIIc (Asymmetric Decaying)')

    data['Class'] = classifications

    df = pd.DataFrame(data)
    return df


# ============================================================================
# ANALYSIS FUNCTIONS
# ============================================================================

def analyze_entropy_pattern(S, N_rev, steps=50):
    """
    Analyze entropy pattern and extract metrics
    """
    # Basic metrics
    S_0 = S[0]
    S_rev = S[N_rev] if N_rev <= steps else np.nan
    S_max = np.max(S)
    S_mean_24 = np.mean(S[:24])
    S_mean_50 = np.mean(S)

    # Find peaks
    peaks, properties = signal.find_peaks(S, height=0.3, distance=2)
    peak_values = S[peaks]
    peak_positions = peaks

    # Find steps where S = 1.0 (within tolerance)
    max_entropy_steps = np.where(np.abs(S - 1.0) < 1e-10)[0]

    return {
        'S_0': S_0,
        'S_rev': S_rev,
        'S_max': S_max,
        'S_mean_24': S_mean_24,
        'S_mean_50': S_mean_50,
        'n_peaks': len(peaks),
        'peak_positions': peak_positions,
        'peak_values': peak_values,
        'max_entropy_steps': max_entropy_steps,
        'revival_diff': abs(S_rev - S_0) if not np.isnan(S_rev) else np.nan
    }


# ============================================================================
# PLOTTING FUNCTIONS
# ============================================================================

def plot_all_overlay(entropy_data, revival_df, steps=50):
    """
    Figure 1: Overlay of all 30 patterns
    """
    plt.figure(figsize=(15, 8))

    # Define colors by class
    class_colors = {
        'Class I (Perfect Alternating)': '#1f77b4',      # blue
        'Class II (Fast Alternating)': '#ff7f0e',        # orange
        'Class IIIa (High-Entropy Sustained)': '#2ca02c', # green
        'Class IIIb (Complex Multi-Mode)': '#d62728',     # red
        'Class IIIc (Asymmetric Decaying)': '#9467bd'     # purple
    }

    # Plot each parameter
    for label in entropy_data.keys():
        row = revival_df[revival_df['Label'] == label].iloc[0]
        color = class_colors.get(row['Class'], '#000000')
        plt.plot(range(steps + 1), entropy_data[label],
                color=color, alpha=0.5, linewidth=1)

    # Add revival markers
    for N_rev in sorted(revival_df['N_revival'].unique()):
        plt.axvline(x=N_rev, color='red', linestyle='--', alpha=0.3)
        plt.text(N_rev, 1.02, f'N={N_rev}', rotation=90, fontsize=8, ha='center')

    # Legend
    legend_elements = [
        Line2D([0], [0], color='#1f77b4', lw=2, label='Class I: Perfect Alternating (ρ=0.5, δ=π/2,3π/2)'),
        Line2D([0], [0], color='#ff7f0e', lw=2, label='Class II: Fast Alternating (ρ=0.5, δ=0,π)'),
        Line2D([0], [0], color='#2ca02c', lw=2, label='Class IIIa: High-Entropy Sustained (ρ=2/3,3/4, δ=π/2,3π/2)'),
        Line2D([0], [0], color='#d62728', lw=2, label='Class IIIb: Complex Multi-Mode (ρ=2/3, δ=0,π)'),
        Line2D([0], [0], color='#9467bd', lw=2, label='Class IIIc: Asymmetric Decaying (ρ=0.75,0.8,0.9)'),
        Line2D([0], [0], color='red', linestyle='--', lw=1, label='Revival steps')
    ]

    plt.xlabel('Time Step', fontsize=12)
    plt.ylabel('Entanglement Entropy S', fontsize=12)
    plt.title('4-Cycle: All 30 Revival Parameters (Dukes 2014 Table 4)', fontsize=14)
    plt.legend(handles=legend_elements, loc='upper right', fontsize=8, ncol=2)
    plt.grid(True, alpha=0.3)
    plt.ylim(-0.05, 1.05)
    plt.xlim(-0.5, steps + 0.5)

    plt.tight_layout()
    plt.savefig('EXP012_4cycle_all_overlay.png', dpi=150, bbox_inches='tight')
    plt.show()

    print("  ✓ Saved: EXP012_4cycle_all_overlay.png")


def plot_individual_grid(entropy_data, revival_df, steps=50):
    """
    Figure 2: Individual subplots for all 30 parameters (6x5 grid)
    """
    fig, axes = plt.subplots(6, 5, figsize=(20, 24))
    axes = axes.flatten()

    # Sort labels for consistent display
    sorted_labels = sorted(entropy_data.keys(),
                          key=lambda x: int(x[1:]))  # Sort by number

    for i, label in enumerate(sorted_labels):
        ax = axes[i]
        S = entropy_data[label]
        row = revival_df[revival_df['Label'] == label].iloc[0]

        # Plot entropy
        ax.plot(range(steps + 1), S, 'b-', linewidth=1.5)
        ax.fill_between(range(steps + 1), 0, S, alpha=0.2, color='skyblue')

        # Mark revival point
        N_rev = row['N_revival']
        ax.axvline(x=N_rev, color='red', linestyle='--', alpha=0.5)
        ax.plot(N_rev, S[N_rev], 'ro', markersize=4)

        # Mark steps where S=1
        max_steps = np.where(np.abs(S - 1.0) < 1e-10)[0]
        ax.plot(max_steps, S[max_steps], 'g*', markersize=3, alpha=0.7)

        # Title with parameters
        title = f"{label}: ρ={row['rho']:.3f}, δ/π={row['delta_over_pi']:.1f}"
        ax.set_title(title, fontsize=8)
        ax.set_xlabel('Step', fontsize=6)
        ax.set_ylabel('S', fontsize=6)
        ax.set_ylim(-0.05, 1.05)
        ax.set_xlim(-0.5, steps + 0.5)
        ax.grid(True, alpha=0.2)
        ax.tick_params(labelsize=6)

        # Add class info in corner
        class_abbrev = row['Class'].split('(')[0].strip()
        ax.text(0.02, 0.98, f"{class_abbrev}\nN={N_rev}",
                transform=ax.transAxes, fontsize=5, verticalalignment='top',
                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

    plt.suptitle('4-Cycle: Individual Entropy Patterns for All 30 Revival Parameters',
                fontsize=16, y=0.98)
    plt.tight_layout()
    plt.savefig('EXP012_4cycle_all_individual.png', dpi=150, bbox_inches='tight')
    plt.show()

    print("  ✓ Saved: EXP012_4cycle_all_individual.png")


def plot_heatmap_sorted(entropy_data, revival_df, steps=50):
    """
    Figure 3: Heatmap sorted by mean entropy
    """
    # Compute mean entropy for sorting
    mean_entropies = {}
    for label, S in entropy_data.items():
        mean_entropies[label] = np.mean(S[:24])  # Use first 24 steps for consistency

    # Sort by mean entropy (descending)
    sorted_labels = sorted(mean_entropies.keys(),
                          key=lambda x: mean_entropies[x], reverse=True)

    # Create heatmap data
    heatmap_data = np.array([entropy_data[label][:steps+1] for label in sorted_labels])

    # Create figure with two subplots
    fig = plt.figure(figsize=(15, 10))
    gs = GridSpec(1, 3, width_ratios=[20, 1, 3])

    ax_heatmap = plt.subplot(gs[0])
    ax_colorbar = plt.subplot(gs[1])
    ax_stats = plt.subplot(gs[2])

    # Plot heatmap
    im = ax_heatmap.imshow(heatmap_data, aspect='auto', cmap='viridis',
                           extent=[0, steps, 0, 30], origin='lower', vmin=0, vmax=1)

    ax_heatmap.set_xlabel('Time Step', fontsize=12)
    ax_heatmap.set_ylabel('Parameter (sorted by mean entropy)', fontsize=12)
    ax_heatmap.set_title('4-Cycle: Entropy Patterns Sorted by Mean Entropy', fontsize=14)

    # Add parameter labels
    ax_heatmap.set_yticks(range(30))
    ax_heatmap.set_yticklabels(sorted_labels, fontsize=8)

    # Add vertical lines at revival periods
    for N_rev in sorted(revival_df['N_revival'].unique()):
        ax_heatmap.axvline(x=N_rev, color='red', linestyle='--', alpha=0.3, linewidth=1)

    # Colorbar
    plt.colorbar(im, cax=ax_colorbar, label='Entropy S')

    # Statistics panel
    ax_stats.axis('off')

    # Create statistics table
    stats_data = []
    for i, label in enumerate(sorted_labels[:10]):  # Top 10
        row = revival_df[revival_df['Label'] == label].iloc[0]
        stats_data.append([
            f"{i+1}",
            label,
            f"{row['rho']:.3f}",
            f"{row['delta_over_pi']:.1f}",
            f"{mean_entropies[label]:.3f}"
        ])

    # Add table to statistics panel
    table = ax_stats.table(cellText=stats_data,
                          colLabels=['Rank', 'Label', 'ρ', 'δ/π', 'S̄₂₄'],
                          cellLoc='center',
                          loc='center',
                          bbox=[0, 0.5, 1, 0.4])

    table.auto_set_font_size(False)
    table.set_fontsize(10)

    # Add summary text
    ax_stats.text(0, 0.3, f"Total parameters: 30", fontsize=12, fontweight='bold')
    ax_stats.text(0, 0.25, f"Max S̄₂₄: {max(mean_entropies.values()):.3f} ({sorted_labels[0]})", fontsize=12)
    ax_stats.text(0, 0.2, f"Min S̄₂₄: {min(mean_entropies.values()):.3f}", fontsize=12)

    # Count parameters that achieve S=1
    s1_count = sum(1 for S in entropy_data.values() if np.max(S) > 0.999)
    ax_stats.text(0, 0.15, f"Parameters with S=1: {s1_count}", fontsize=12)

    plt.tight_layout()
    plt.savefig('EXP012_4cycle_heatmap.png', dpi=150, bbox_inches='tight')
    plt.show()

    print("  ✓ Saved: EXP012_4cycle_heatmap.png")


# ============================================================================
# MAIN SIMULATION AND OUTPUT
# ============================================================================

def main():
    print("=" * 80)
    print("EXP012: 4-Cycle Quantum Walk Entanglement Entropy Simulation")
    print("Based on Dukes (2014) Table 4 Revival Parameters")
    print("=" * 80)

    # Simulation parameters
    steps = 50
    k = 4

    # Get revival parameters
    revival_df = create_revival_table_4cycle()

    print(f"\nSimulating {len(revival_df)} parameters for {steps} steps...")
    print("-" * 80)

    # Simulate all parameters
    entropy_data = {}

    for idx, row in revival_df.iterrows():
        label = row['Label']
        rho = row['rho']
        delta = row['delta']
        N_rev = row['N_revival']

        print(f"  {label}: ρ={rho:.3f}, δ/π={row['delta_over_pi']:.1f}, N_rev={N_rev}")

        # Run simulation
        S = simulate_quantum_walk(rho, delta, steps=steps, k=k)
        entropy_data[label] = S

    print("-" * 80)
    print("Simulation complete!")

    # ========================================================================
    # VERIFICATION OF REVIVAL CONDITION
    # ========================================================================

    print("\n" + "=" * 80)
    print("VERIFICATION OF REVIVAL CONDITION")
    print("=" * 80)

    print(f"\n{'Label':<6} {'ρ':<6} {'δ/π':<6} {'N_rev':<6} {'S(0)':<8} {'S(N_rev)':<10} {'Diff':<8} {'Status':<8} {'Class':<30}")
    print("-" * 100)

    revival_summary = []
    all_good = True

    for label in sorted(entropy_data.keys(), key=lambda x: int(x[1:])):
        row = revival_df[revival_df['Label'] == label].iloc[0]
        N_rev = row['N_revival']
        S = entropy_data[label]
        S_0 = S[0]
        S_rev = S[N_rev]
        diff = abs(S_rev - S_0)

        status = "✓" if diff < 1e-10 else " "
        if diff >= 1e-10:
            all_good = False

        print(f"{label:<6} {row['rho']:<6.3f} {row['delta_over_pi']:<6.1f} {N_rev:<6} "
              f"{S_0:<8.4f} {S_rev:<10.4f} {diff:<8.4f} {status:<8} {row['Class'][:30]}")

        revival_summary.append({
            'Label': label,
            'ρ': row['rho'],
            'δ/π': row['delta_over_pi'],
            'N_rev': N_rev,
            'S(0)': S_0,
            'S(N_rev)': S_rev,
            'Diff': diff,
            'Perfect Revival': diff < 1e-10,
            'Class': row['Class']
        })

    print("-" * 100)
    if all_good:
        print("✅ All parameters show perfect revival!")
    else:
        print("❌ Some parameters do not show perfect revival with this convention.")

    # ========================================================================
    # MAXIMUM ENTROPY ACHIEVEMENT
    # ========================================================================

    print("\n" + "=" * 80)
    print("MAXIMUM ENTROPY ACHIEVEMENT (S = 1.0)")
    print("=" * 80)

    print(f"\n{'Label':<6} {'ρ':<6} {'δ/π':<6} {'N_rev':<6} {'S_max':<8} {'Steps at S=1':<40}")
    print("-" * 80)

    max_entropy_params = []
    max_counts = []

    for label in sorted(entropy_data.keys(), key=lambda x: int(x[1:])):
        row = revival_df[revival_df['Label'] == label].iloc[0]
        S = entropy_data[label]
        S_max = np.max(S)

        # Find steps where S ≈ 1.0
        max_steps = np.where(np.abs(S - 1.0) < 1e-10)[0]

        if len(max_steps) > 0:
            steps_str = ', '.join([str(step) for step in max_steps[:10]])
            if len(max_steps) > 10:
                steps_str += f", ... ({len(max_steps)} total)"
            print(f"{label:<6} {row['rho']:<6.3f} {row['delta_over_pi']:<6.1f} {row['N_revival']:<6} "
                  f"{S_max:<8.4f} {steps_str:<40}")
            max_entropy_params.append(label)
            max_counts.append((label, len(max_steps)))
        else:
            print(f"{label:<6} {row['rho']:<6.3f} {row['delta_over_pi']:<6.1f} {row['N_revival']:<6} "
                  f"{S_max:<8.4f} {'Never reaches 1.0':<40}")

    print("-" * 80)
    print(f"Parameters achieving S=1: {len(max_entropy_params)}")
    print(f"All ρ=0.5 parameters achieve S=1, no ρ≠0.5 parameters do.")

    # Most frequent S=1
    if max_counts:
        max_counts.sort(key=lambda x: x[1], reverse=True)
        best_max_label, best_max_count = max_counts[0]
        best_max_row = revival_df[revival_df['Label'] == best_max_label].iloc[0]
        print(f"\n🎯 Most frequent S=1 ({best_max_count} steps):")
        print(f"   {best_max_label}: ρ={best_max_row['rho']:.3f}, δ/π={best_max_row['delta_over_pi']:.1f}")

    # ========================================================================
    # MEAN ENTROPY RANKING
    # ========================================================================

    print("\n" + "=" * 80)
    print("MEAN ENTROPY RANKING (S̄₂₄ - first 24 steps)")
    print("=" * 80)

    # Calculate mean entropies
    mean_entropies_24 = {}
    mean_entropies_50 = {}

    for label, S in entropy_data.items():
        mean_entropies_24[label] = np.mean(S[:24])
        mean_entropies_50[label] = np.mean(S)

    # Sort by mean entropy (descending)
    sorted_by_mean = sorted(mean_entropies_24.keys(),
                           key=lambda x: mean_entropies_24[x], reverse=True)

    print(f"\n{'Rank':<6} {'Label':<6} {'ρ':<8} {'δ/π':<8} {'N_rev':<8} {'S̄₂₄':<8} {'S̄₅₀':<8} {'Class':<30}")
    print("-" * 90)

    for rank, label in enumerate(sorted_by_mean, 1):
        row = revival_df[revival_df['Label'] == label].iloc[0]
        print(f"{rank:<6} {label:<6} {row['rho']:<8.3f} {row['delta_over_pi']:<8.1f} "
              f"{row['N_revival']:<8} {mean_entropies_24[label]:<8.3f} "
              f"{mean_entropies_50[label]:<8.3f} {row['Class'][:30]}")

    # ========================================================================
    # FASTEST TO REACH S=1
    # ========================================================================

    print("\n" + "=" * 80)
    print("FASTEST TO REACH MAXIMUM ENTROPY")
    print("=" * 80)

    first_max_times = []
    for label in max_entropy_params:  # Only consider parameters that achieve S=1
        S = entropy_data[label]
        first_max = np.where(np.abs(S - 1.0) < 1e-10)[0][0]
        first_max_times.append((label, first_max))

    if first_max_times:
        first_max_times.sort(key=lambda x: x[1])
        print(f"\n{'Label':<6} {'First step at S=1':<20} {'ρ':<8} {'δ/π':<8}")
        print("-" * 50)

        for label, first_time in first_max_times[:5]:  # Top 5 fastest
            row = revival_df[revival_df['Label'] == label].iloc[0]
            print(f"{label:<6} {first_time:<20} {row['rho']:<8.3f} {row['delta_over_pi']:<8.1f}")

        fastest_label, fastest_time = first_max_times[0]
        fastest_row = revival_df[revival_df['Label'] == fastest_label].iloc[0]
        print(f"\n⚡ Fastest to reach S=1 (step {fastest_time}):")
        print(f"   {fastest_label}: ρ={fastest_row['rho']:.3f}, δ/π={fastest_row['delta_over_pi']:.1f}")

    # ========================================================================
    # CLASS SUMMARY
    # ========================================================================

    print("\n" + "=" * 80)
    print("CLASS SUMMARY")
    print("=" * 80)

    # Group by class
    class_groups = {}
    for idx, row in revival_df.iterrows():
        class_name = row['Class']
        if class_name not in class_groups:
            class_groups[class_name] = []
        class_groups[class_name].append(row['Label'])

    for class_name, labels in class_groups.items():
        print(f"\n{class_name}: {len(labels)} parameters")
        print(f"  Labels: {', '.join(labels)}")

        # Calculate average metrics for this class
        class_means_24 = [mean_entropies_24[label] for label in labels]
        class_means_50 = [mean_entropies_50[label] for label in labels]

        print(f"  Avg S̄₂₄: {np.mean(class_means_24):.3f} ± {np.std(class_means_24):.3f}")
        print(f"  Avg S̄₅₀: {np.mean(class_means_50):.3f} ± {np.std(class_means_50):.3f}")

        # Check if class achieves S=1
        achieves_max = any(np.max(entropy_data[label]) > 0.999 for label in labels)
        print(f"  Achieves S=1: {'Yes' if achieves_max else 'No'}")

    # ========================================================================
    # OPTIMAL PARAMETERS SUMMARY
    # ========================================================================

    print("\n" + "=" * 80)
    print("OPTIMAL PARAMETERS BY CATEGORY")
    print("=" * 80)

    # Highest mean entropy
    best_label = sorted_by_mean[0]
    best_row = revival_df[revival_df['Label'] == best_label].iloc[0]
    print(f"\n🏆 HIGHEST MEAN ENTROPY (S̄₂₄ = {mean_entropies_24[best_label]:.3f}):")
    print(f"   {best_label}: ρ={best_row['rho']:.3f}, δ/π={best_row['delta_over_pi']:.1f}, "
          f"N_rev={best_row['N_revival']}")
    print(f"   Class: {best_row['Class']}")

    # Most frequent S=1
    if max_counts:
        best_max_label, best_max_count = max_counts[0]
        best_max_row = revival_df[revival_df['Label'] == best_max_label].iloc[0]
        print(f"\n🎯 MOST FREQUENT MAXIMUM ENTROPY ({best_max_count} steps):")
        print(f"   {best_max_label}: ρ={best_max_row['rho']:.3f}, δ/π={best_max_row['delta_over_pi']:.1f}")
        print(f"   Class: {best_max_row['Class']}")

    # Fastest to reach S=1
    if first_max_times:
        fastest_label, fastest_time = first_max_times[0]
        fastest_row = revival_df[revival_df['Label'] == fastest_label].iloc[0]
        print(f"\n⚡ FASTEST TO REACH MAXIMUM ENTROPY (step {fastest_time}):")
        print(f"   {fastest_label}: ρ={fastest_row['rho']:.3f}, δ/π={fastest_row['delta_over_pi']:.1f}")
        print(f"   Class: {fastest_row['Class']}")

    # ========================================================================
    # GENERATE PLOTS
    # ========================================================================

    print("\n" + "=" * 80)
    print("GENERATING PLOTS")
    print("=" * 80)

    print("\nGenerating Figure 1: Overlay of all patterns...")
    plot_all_overlay(entropy_data, revival_df, steps)

    print("\nGenerating Figure 2: Individual subplots grid...")
    plot_individual_grid(entropy_data, revival_df, steps)

    print("\nGenerating Figure 3: Heatmap sorted by mean entropy...")
    plot_heatmap_sorted(entropy_data, revival_df, steps)

    # ========================================================================
    # FINAL SUMMARY
    # ========================================================================

    print("\n" + "=" * 80)
    print("EXP012 SIMULATION COMPLETE")
    print("=" * 80)
    print(f"\n✅ Generated 3 image files:")
    print("   1. EXP012_4cycle_all_overlay.png")
    print("   2. EXP012_4cycle_all_individual.png")
    print("   3. EXP012_4cycle_heatmap.png")
    print(f"\n📊 Key findings:")
    print(f"   - Total parameters simulated: {len(entropy_data)}")
    print(f"   - Parameters with perfect revival: {sum(1 for item in revival_summary if item['Perfect Revival'])}")
    print(f"   - Parameters achieving S=1: {len(max_entropy_params)}")
    print(f"   - Maximum mean entropy: {mean_entropies_24[best_label]:.3f} ({best_label})")
    print("=" * 80)


if __name__ == "__main__":
    main()